services:
  app:
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - ${SERVICE_PORT}:8000
    working_dir: /opt/project/src
    volumes:
      - ..:/opt/project

  builder:
    build:
      context: ..
      target: builder
    depends_on:
      - postgres
    env_file:
      - env.svc.app
    working_dir: /opt/project/src
    volumes:
      - ..:/opt/project
