services:
  app:
    depends_on:
      - postgres

  builder:
    depends_on:
      - postgres

  postgres:
    image: postgres:12-alpine
    volumes:
      - pg-data:/var/lib/postgresql/data
    env_file:
      - env.svc.postgres



volumes:
  pg-data:
    driver: local
