services:
  app:
    depends_on:
      - postgres

  postgres:
    image: postgres:12-alpine
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=local
      - POSTGRES_USER=local
      - POSTGRES_PASSWORD=local


volumes:
  pg-data:
    driver: local
